//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class anaartma
    {
        public string cod_art { get; set; }
        public int nr_riga { get; set; }
        public string cod_dep { get; set; }
        public string cod_mag { get; set; }
        public string corsia { get; set; }
        public Nullable<int> nr_col { get; set; }
        public Nullable<int> nr_rip { get; set; }
        public string flag_imp { get; set; }
        public Nullable<double> seq_pos { get; set; }
        public string flag_doppio { get; set; }
        public string flag_data_scad { get; set; }
        public string flag_lotto { get; set; }
        public Nullable<int> prog_chiave { get; set; }
        public Nullable<int> gia_min { get; set; }
        public string tipo_riempimento { get; set; }
        public string flag_nopz { get; set; }
        public Nullable<double> cap_prel { get; set; }
        public Nullable<double> cap_sco { get; set; }
        public Nullable<double> gia_min_prel { get; set; }
        public Nullable<double> gia_min_sco { get; set; }
        public Nullable<int> gia_min_co { get; set; }
    }
}
