//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class magartubiass
    {
        public string cod_art { get; set; }
        public string cod_art_padre { get; set; }
        public int freq_assoc { get; set; }
    
        public virtual magartubifreq magartubifreq { get; set; }
    }
}
