//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordclidet
    {
        public int anno_ord { get; set; }
        public int nr_ord { get; set; }
        public int nr_riga { get; set; }
        public int nr_riga_ord { get; set; }
        public string tipo_riga { get; set; }
        public string cod_dep { get; set; }
        public Nullable<System.DateTime> data_ord { get; set; }
        public Nullable<System.DateTime> data_cons { get; set; }
        public string cod_doc { get; set; }
        public string cod_giro { get; set; }
        public string cod_age { get; set; }
        public Nullable<int> cod_cli { get; set; }
        public Nullable<int> cod_gda { get; set; }
        public Nullable<int> cod_grp { get; set; }
        public Nullable<int> cod_int { get; set; }
        public Nullable<int> cod_ins { get; set; }
        public string rif { get; set; }
        public string raggrupp_fatt { get; set; }
        public string referenza { get; set; }
        public string cod_rep { get; set; }
        public string cod_art { get; set; }
        public string des_art { get; set; }
        public string cod_um { get; set; }
        public string cod_iva { get; set; }
        public string tipo_art { get; set; }
        public string cod_linea_comm { get; set; }
        public string cod_sett_comm { get; set; }
        public string cod_fam_comm { get; set; }
        public string cod_sott_comm { get; set; }
        public Nullable<double> qta_ordinata { get; set; }
        public Nullable<double> qta_co { get; set; }
        public Nullable<double> qta_cf { get; set; }
        public Nullable<double> qta_pz { get; set; }
        public Nullable<double> qta_pe { get; set; }
        public string omaggio { get; set; }
        public string cod_mag { get; set; }
        public Nullable<double> prezzo_unitario { get; set; }
        public string cod_prom { get; set; }
        public Nullable<double> sco_promozione { get; set; }
        public Nullable<double> sco_cliart { get; set; }
        public Nullable<double> sco_listino { get; set; }
        public Nullable<double> sco_incondiz1 { get; set; }
        public Nullable<double> sco_incondiz2 { get; set; }
        public Nullable<double> sco_incondiz3 { get; set; }
        public Nullable<double> sco_fine_anno { get; set; }
        public Nullable<double> importo { get; set; }
        public Nullable<double> provvigione_agente { get; set; }
        public Nullable<double> qta_in_sped { get; set; }
        public Nullable<double> qta_in_sped_co { get; set; }
        public Nullable<double> qta_in_sped_cf { get; set; }
        public Nullable<double> qta_in_sped_pz { get; set; }
        public Nullable<double> qta_in_sped_pe { get; set; }
        public Nullable<double> qta_spedita { get; set; }
        public string flag_evaso { get; set; }
        public string stato_evasione { get; set; }
        public string flag_comm_su_ord { get; set; }
        public string flag_comm_su_doc { get; set; }
        public string flag_comm_su_fatt { get; set; }
        public string commento { get; set; }
        public string cod_prel { get; set; }
        public Nullable<System.DateTime> data_prel { get; set; }
        public string flag_prz_mano { get; set; }
        public string cod_prom_gen { get; set; }
        public Nullable<int> priorita_prom_gen { get; set; }
        public Nullable<int> nr_riga_gen { get; set; }
        public string lotto_manuale { get; set; }
        public string flag_ass { get; set; }
        public string flag_automatica { get; set; }
        public string flag_magauto { get; set; }
        public string cod_imb { get; set; }
        public Nullable<double> qta_cons_imb { get; set; }
        public Nullable<double> qta_resi_imb { get; set; }
        public string flag_stppre { get; set; }
        public string tipo_um_input { get; set; }
        public string flag_trasm_asc { get; set; }
        public string flag_prezzo_prom { get; set; }
        public string art_ec { get; set; }
        public string flag_esplosa { get; set; }
        public Nullable<int> riga_esplosa { get; set; }
        public Nullable<double> prezzo_orig { get; set; }
        public Nullable<double> qta_confermata { get; set; }
        public Nullable<double> sco_valore1 { get; set; }
        public Nullable<double> sco_valore2 { get; set; }
        public Nullable<double> sco_valore3 { get; set; }
        public string cod_accisa { get; set; }
        public string cod_contr { get; set; }
        public Nullable<double> prezzo_ivato { get; set; }
        public string cod_age_eb3s { get; set; }
        public string flag_offerta { get; set; }
        public string flag_fine_offerta { get; set; }
        public string no_accisa { get; set; }
    }
}
